### ISSUE TITLE
Move data to huggingface hub

### ISSUE THREAD

**Issue by harveenchadha** [rahular/varta#1]
I have reviewed the data links and discovered that the person making the request is required to pay for downloads. This practice goes against the unsaid principles of open source datasets and my recommendation would be to relocate this data to the Hugging Face Hub.

Should you deem it necessary to address this issue, I am ready and willing to provide my assistance.

**Comment by rahular** [comment]
Thanks @harveenchadha, it will be up on HF soon. Will keep you updated here!
