### ISSUE TITLE
Not able to recreate the dataset using the crawler

### ISSUE THREAD

**Issue by haresh121** [rahular/varta#2]
Hi @rahular ,

I was trying to use the `varta` dataset, after following the instructions provided by you to scrape the URL's present in the HF dataset, I am getting the `403 Access Forbidden error` for almost all the rows.

Here is the image attached with the error

Please let me know how I can process the URL's. 

<img width="1138" alt="image" src="https://github.com/rahular/varta/assets/34397532/8fc888a7-0db8-41b0-be26-f7a8f9f854db">

**Comment by rahular** [comment]
Hi, I just manually tried to access a URL ([link](https://pwa-api.dailyhunt.in/api/v100/moredetails?morecontenturl=http://api-news.dailyhunt.in/api/v2/posts/article/content/400000000?useWidgetPosition=false&feedConfigKey=HASHTAG_CHRONO&ignoreTrack=true)) and it seems to work.

I assume you are being rate limited or your IP might have been blocked. I would recommend you slow down your access rate by adjusting the number of concurrent requests you make (change [here](https://github.com/rahular/varta/blob/main/crawler/dh_scrapy/settings.py#L27)) or try accessing it from a different IP.

Let me know if that works for you.

**Comment by haresh121** [comment]
Thanks for the reply,

Actually I am still facing the same error, although after decreasing the number of concurrent requests to 2 !
Do you have any endpoint where I can get the aggregated data containing the `title`, the `content` and the other features ?

Or do you have any other fixes for the same ?

**Comment by rahular** [comment]
Are you able to get a response through the [link](https://pwa-api.dailyhunt.in/api/v100/moredetails?morecontenturl=http://api-news.dailyhunt.in/api/v2/posts/article/content/400000000?useWidgetPosition=false&feedConfigKey=HASHTAG_CHRONO&ignoreTrack=true)? If not, your IP is probably blocked, and you have to use a different one.

**Comment by haresh121** [comment]
I am able to access the link actually, and the problem is with the number of concurrent requests.
After changing it to 4 it started working !

And also accessing it with another IP address is also working.

Thank you for the help!!
